# Generated by Django 5.2.7 on 2025-11-19 13:35

import apps.productos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_alter_producto_codigo_barras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=apps.productos.models.producto_imagen_path),
        ),
    ]
