# Generated by Django 4.2.28 on 2026-02-28 18:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productos', '0008_product_display_config'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedproductfilter',
            options={'ordering': ['-es_favorito', '-veces_usado', '-fecha_modificacion'], 'verbose_name': 'Filtro Guardado', 'verbose_name_plural': 'Filtros Guardados'},
        ),
        migrations.AddField(
            model_name='savedproductfilter',
            name='color',
            field=models.CharField(choices=[('emerald', 'Verde'), ('blue', 'Azul'), ('purple', 'Morado'), ('orange', 'Naranja'), ('red', 'Rojo'), ('yellow', 'Amarillo')], default='emerald', max_length=20, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='savedproductfilter',
            name='config_vista',
            field=models.JSONField(blank=True, default=dict, help_text='Configuración específica de visualización para esta vista guardada', verbose_name='Configuración de Vista'),
        ),
        migrations.AddField(
            model_name='savedproductfilter',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='savedproductfilter',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='savedproductfilter',
            name='icono',
            field=models.CharField(default='filter', help_text='Nombre del icono de lucide', max_length=50, verbose_name='Icono'),
        ),
        migrations.AddField(
            model_name='savedproductfilter',
            name='veces_usado',
            field=models.PositiveIntegerField(default=0, verbose_name='Veces Usado'),
        ),
        migrations.AlterField(
            model_name='savedproductfilter',
            name='filtros',
            field=models.JSONField(default=dict, help_text='Incluye: categoria, stock_bajo, sin_imagen, orden, vista, etc.', verbose_name='Filtros'),
        ),
        migrations.AlterUniqueTogether(
            name='savedproductfilter',
            unique_together={('user', 'nombre')},
        ),
    ]
