# Generated by Django 4.2.28 on 2026-03-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_alter_savedproductfilter_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='controla_stock',
            field=models.BooleanField(default=True, verbose_name='Controlar stock'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
