# Generated by Django 4.2.28 on 2026-03-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_producto_controla_stock_alter_producto_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
        migrations.AddField(
            model_name='producto',
            name='incluye_iva',
            field=models.BooleanField(default=True, verbose_name='Precio incluye IVA'),
        ),
        migrations.AddField(
            model_name='producto',
            name='iva_porcentaje',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=5, verbose_name='IVA %'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio base'),
        ),
    ]
