# Generated by Django 4.2.28 on 2026-03-03 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_add_precio_base_iva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='iva_porcentaje',
        ),
    ]
