# Generated by Django 4.2.28 on 2026-03-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0015_add_audit_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='SKU / Código interno'),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_minimo',
            field=models.PositiveIntegerField(blank=True, default=5, null=True, verbose_name='Stock mínimo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_producto',
            field=models.CharField(choices=[('fisico', 'Producto físico'), ('servicio', 'Servicio'), ('combo', 'Combo / Plato'), ('insumo', 'Insumo / Materia prima')], default='fisico', max_length=20, verbose_name='Tipo de producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('unidad', 'Unidad'), ('porcion', 'Porción'), ('kg', 'Kilogramo'), ('g', 'Gramo'), ('l', 'Litro'), ('ml', 'Mililitro'), ('caja', 'Caja'), ('paquete', 'Paquete'), ('docena', 'Docena')], default='unidad', max_length=20, verbose_name='Unidad de medida'),
        ),
    ]
