# Generated by Django 4.2.28 on 2026-03-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0016_add_product_metadata_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.CharField(default='PRD-0000', max_length=50, unique=True, verbose_name='SKU / Código interno'),
            preserve_default=False,
        ),
    ]
