# Generated by Django 4.2.28 on 2026-03-06 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_cliente_es_favorito_cliente_total_compras_and_more'),
        ('ventas', '0008_remove_global_unique_numero_factura'),
        ('transacciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.cliente'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='notas',
            field=models.TextField(blank=True, null=True, verbose_name='Notas Adicionales'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='referencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia Bancaria'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='tipo_transaccion',
            field=models.CharField(choices=[('venta', 'Pago de Venta'), ('pago_credito', 'Pago de Crédito'), ('devolucion', 'Devolución'), ('abono', 'Abono a Cuenta')], default='venta', max_length=20, verbose_name='Tipo de Transacción'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='metodo_pago',
            field=models.CharField(choices=[('cash', 'Efectivo'), ('card', 'Tarjeta'), ('transfer', 'Transferencia'), ('credit', 'Crédito')], max_length=50),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='transaction_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.venta'),
        ),
    ]
