# Generated by Django 4.2.28 on 2026-03-06 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0002_transaccion_cliente_transaccion_notas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='venta_total_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Snapshot del total de la venta al momento de la transacción', max_digits=10, null=True, verbose_name='Total de Venta (Snapshot)'),
        ),
    ]
