# Generated by Django 5.1.7 on 2025-04-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='direccion_negocio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección del negocio/local'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='email_negocio',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email negocio/local'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ruc_negocio',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RUC negocio/local'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono_negocio',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono del negocio/local'),
        ),
    ]
