# Generated by Django 5.1.7 on 2025-04-12 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_direccion_negocio_usuario_email_negocio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_negocio', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion_negocio', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono_negocio', models.CharField(blank=True, max_length=20, null=True)),
                ('ruc_negocio', models.CharField(blank=True, max_length=20, null=True)),
                ('email_negocio', models.EmailField(blank=True, max_length=254, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
