# Generated by Django 5.1.7 on 2025-04-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='formato_fecha',
            field=models.CharField(default='d/m/Y', max_length=20, verbose_name='Formato de Fecha'),
        ),
        migrations.AddField(
            model_name='business',
            name='iva_porcentaje',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=5, verbose_name='Porcentaje de IVA'),
        ),
        migrations.AddField(
            model_name='business',
            name='mensaje_factura',
            field=models.TextField(blank=True, default='¡Gracias por su compra!', null=True, verbose_name='Mensaje en Factura'),
        ),
        migrations.AddField(
            model_name='business',
            name='moneda',
            field=models.CharField(default='$', max_length=10, verbose_name='Símbolo de Moneda'),
        ),
        migrations.AddField(
            model_name='business',
            name='mostrar_logo_en_factura',
            field=models.BooleanField(default=True, verbose_name='Mostrar Logo en Factura'),
        ),
        migrations.AddField(
            model_name='business',
            name='politica_devolucion',
            field=models.TextField(blank=True, default='Para devoluciones, presente este comprobante dentro de los próximos 7 días.', null=True, verbose_name='Política de Devolución'),
        ),
    ]
