# Generated by Django 5.1.7 on 2025-04-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_business_formato_fecha_business_iva_porcentaje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='business_logos/'),
        ),
    ]
