# Generated by Django 5.1.7 on 2025-04-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_business_ciudad_business_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='custom_brand_name',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='business',
            name='default_view',
            field=models.CharField(default='grid', max_length=10),
        ),
        migrations.AddField(
            model_name='business',
            name='primary_color',
            field=models.CharField(default='#10b981', max_length=7),
        ),
        migrations.AddField(
            model_name='business',
            name='secondary_color',
            field=models.CharField(default='#6366f1', max_length=7),
        ),
        migrations.AddField(
            model_name='business',
            name='show_product_images',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='business',
            name='use_custom_brand_name',
            field=models.BooleanField(default=False),
        ),
    ]
