# Generated by Django 5.1.7 on 2025-04-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_business_custom_brand_name_business_default_view_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
    ]
