# Generated by Django 5.1.7 on 2025-04-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_business_dark_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='use_custom_logo',
            field=models.BooleanField(default=False),
        ),
    ]
