# Generated by Django 5.1.7 on 2025-04-23 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usuarios', '0008_business_use_custom_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='formato_fecha',
            field=models.CharField(default='d/m/Y', max_length=20, verbose_name='Formato de fecha'),
        ),
        migrations.AlterField(
            model_name='business',
            name='mensaje_factura',
            field=models.TextField(blank=True, default='¡Gracias por su compra!', null=True, verbose_name='Mensaje en factura'),
        ),
        migrations.AlterField(
            model_name='business',
            name='moneda',
            field=models.CharField(default='$', max_length=10, verbose_name='Símbolo de moneda'),
        ),
        migrations.AlterField(
            model_name='business',
            name='mostrar_logo_en_factura',
            field=models.BooleanField(default=True, verbose_name='Mostrar logo en factura'),
        ),
        migrations.AlterField(
            model_name='business',
            name='politica_devolucion',
            field=models.TextField(blank=True, default='Para devoluciones, presente este comprobante dentro de los próximos 7 días.', null=True, verbose_name='Política de devolución'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email_negocio',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email del negocio/local'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Grupos a los que pertenece este usuario.', related_name='custom_user_groups', related_query_name='custom_user_group', to='auth.group', verbose_name='Grupos'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ruc_negocio',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RUC del negocio/local'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Permisos específicos para este usuario.', related_name='custom_user_permissions', related_query_name='custom_user_permission', to='auth.permission', verbose_name='Permisos de usuario'),
        ),
    ]
