# Generated by Django 5.1.7 on 2025-04-23 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usuarios', '0009_alter_business_formato_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='formato_fecha',
            field=models.CharField(default='d/m/Y', max_length=20, verbose_name='Formato de Fecha'),
        ),
        migrations.AlterField(
            model_name='business',
            name='mensaje_factura',
            field=models.TextField(blank=True, default='¡Gracias por su compra!', null=True, verbose_name='Mensaje en Factura'),
        ),
        migrations.AlterField(
            model_name='business',
            name='moneda',
            field=models.CharField(default='$', max_length=10, verbose_name='Símbolo de Moneda'),
        ),
        migrations.AlterField(
            model_name='business',
            name='mostrar_logo_en_factura',
            field=models.BooleanField(default=True, verbose_name='Mostrar Logo en Factura'),
        ),
        migrations.AlterField(
            model_name='business',
            name='politica_devolucion',
            field=models.TextField(blank=True, default='Para devoluciones, presente este comprobante dentro de los próximos 7 días.', null=True, verbose_name='Política de Devolución'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email_negocio',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email negocio/local'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_groups', related_query_name='custom_user_group', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ruc_negocio',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RUC negocio/local'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_permissions', related_query_name='custom_user_permission', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
