# Generated by Django 5.1.7 on 2025-05-10 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_alter_business_formato_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='modo_operacion',
            field=models.CharField(choices=[('restaurante', 'Modo Restaurante'), ('retail', 'Modo Retail/Supermercado')], default='restaurante', max_length=20),
        ),
    ]
