# Generated by Django 4.2.28 on 2026-02-28 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_add_enable_orders'),
        ('usuarios', '0013_business_enable_orders_alter_business_enable_kds_and_more'),
    ]

    operations = [
    ]
