# Generated by Django 4.2.28 on 2026-02-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_merge_20260228_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='plan',
            field=models.CharField(choices=[('free', 'Plan Gratuito'), ('pro', 'Plan Pro'), ('enterprise', 'Plan Enterprise')], default='free', max_length=20, verbose_name='Plan de Suscripción'),
        ),
        migrations.AlterField(
            model_name='business',
            name='iva_porcentaje',
            field=models.DecimalField(decimal_places=2, default=15.0, help_text='Tarifa vigente: 15%. Históricas: 0%, 12%, 14%', max_digits=5, verbose_name='Porcentaje de IVA'),
        ),
    ]
