# Generated by Django 4.2.28 on 2026-02-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_business_plan_alter_business_iva_porcentaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='ambiente_sri',
            field=models.CharField(choices=[('1', 'Pruebas'), ('2', 'Producción')], default='1', max_length=1, verbose_name='Ambiente SRI'),
        ),
        migrations.AddField(
            model_name='business',
            name='establecimiento',
            field=models.CharField(blank=True, help_text='3 dígitos (ej: 001)', max_length=3, null=True, verbose_name='Establecimiento'),
        ),
        migrations.AddField(
            model_name='business',
            name='obligado_contabilidad',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2, verbose_name='Obligado a llevar contabilidad'),
        ),
        migrations.AddField(
            model_name='business',
            name='punto_emision',
            field=models.CharField(blank=True, help_text='3 dígitos (ej: 001)', max_length=3, null=True, verbose_name='Punto de Emisión'),
        ),
        migrations.AddField(
            model_name='business',
            name='razon_social_legal',
            field=models.CharField(blank=True, help_text='Exactamente como aparece en el RUC', max_length=300, null=True, verbose_name='Razón Social Legal'),
        ),
        migrations.AddField(
            model_name='business',
            name='regimen_rimpe',
            field=models.CharField(blank=True, choices=[('', 'No aplica'), ('RIMPE', 'RIMPE'), ('RIMPE_EMPRENDEDOR', 'RIMPE - Emprendedor'), ('NO', 'NO')], max_length=20, null=True, verbose_name='Régimen RIMPE'),
        ),
        migrations.AddField(
            model_name='business',
            name='tipo_emision',
            field=models.CharField(choices=[('1', 'Emisión Normal'), ('2', 'Emisión por Indisponibilidad')], default='1', max_length=1, verbose_name='Tipo de Emisión'),
        ),
    ]
