# Generated by Django 4.2.28 on 2026-02-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_business_ambiente_sri_business_establecimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Logo de Empresa'),
        ),
        migrations.AlterField(
            model_name='business',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='business_logos/', verbose_name='Logo de Personalización'),
        ),
    ]
