# Generated by Django 4.2.28 on 2026-03-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0017_business_company_logo_alter_business_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='secuencial_actual',
            field=models.PositiveIntegerField(default=1, help_text='Número secuencial que se autoincrementa con cada factura', verbose_name='Secuencial Actual de Facturación'),
        ),
    ]
