# Generated by Django 4.2.28 on 2026-03-06 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0018_business_secuencial_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='establecimiento',
            field=models.CharField(default='001', help_text='3 dígitos (ej: 001)', max_length=3, verbose_name='Establecimiento'),
        ),
        migrations.AlterField(
            model_name='business',
            name='punto_emision',
            field=models.CharField(default='001', help_text='3 dígitos (ej: 001)', max_length=3, verbose_name='Punto de Emisión'),
        ),
        migrations.AlterField(
            model_name='business',
            name='secuencial_actual',
            field=models.PositiveIntegerField(default=1, help_text='Número secuencial que se autoincrementa con cada factura. NO modificar manualmente.', verbose_name='Secuencial Actual de Facturación'),
        ),
    ]
