# Generated by Django 5.1.7 on 2025-04-04 15:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nombre'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AddField(
            model_name='cliente',
            name='ciudad',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='clase',
            field=models.CharField(choices=[('a', 'Clase A'), ('b', 'Clase B'), ('c', 'Clase C')], default='c', max_length=10, verbose_name='Clase'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='comentarios',
            field=models.TextField(blank=True, null=True, verbose_name='Comentarios'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='dia_corte',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Día de Corte'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido')], default='activo', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='facturas_vencidas',
            field=models.PositiveIntegerField(default=0, verbose_name='Facturas Vencidas'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='forma_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('credito', 'Crédito'), ('transferencia', 'Transferencia'), ('cheque', 'Cheque')], default='efectivo', max_length=20, verbose_name='Forma de Pago'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='grupo',
            field=models.CharField(choices=[('regular', 'Regular'), ('vip', 'VIP'), ('corporativo', 'Corporativo')], default='regular', max_length=20, verbose_name='Grupo'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='imprimir_factura',
            field=models.BooleanField(default=True, verbose_name='Imprimir en factura'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_registro',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Cliente desde'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='identificacion',
            field=models.CharField(default='PENDIENTE', max_length=20, verbose_name='Cédula/RUC'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono 1'),
        ),
    ]
