# Generated by Django 5.1.7 on 2025-04-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_cliente_options_cliente_ciudad_cliente_clase_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='clase',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='comentarios',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='dia_corte',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='facturas_vencidas',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='forma_pago',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='imprimir_factura',
        ),
        migrations.AddField(
            model_name='cliente',
            name='credito',
            field=models.IntegerField(choices=[(0, 'Sin crédito'), (15, '15 días'), (30, '30 días'), (45, '45 días'), (60, '60 días'), (90, '90 días')], default=0, verbose_name='Crédito (días)'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cupo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cupo'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='notas',
            field=models.TextField(blank=True, null=True, verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='razon_social',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Razón Social'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tasa_descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Tasa de descuento (%)'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tasa_recargo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Tasa de recargo (%)'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='identificacion',
            field=models.CharField(max_length=20, verbose_name='Identificación'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
    ]
