# Generated by Django 5.1.7 on 2025-04-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_remove_cliente_ciudad_remove_cliente_clase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='calificacion',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='B', max_length=1, verbose_name='Calificación'),
        ),
    ]
