# Generated by Django 5.1.7 on 2025-04-04 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_cliente_calificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='calificacion',
        ),
    ]
