# Generated by Django 5.1.7 on 2025-04-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_remove_cliente_calificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
    ]
