# Generated by Django 4.2.28 on 2026-03-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_cliente_usuario_creador'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='es_favorito',
            field=models.BooleanField(default=False, verbose_name='Cliente Favorito'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='total_compras',
            field=models.IntegerField(default=0, verbose_name='Total de Compras'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='total_gastado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Gastado'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ultima_compra',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última Compra'),
        ),
    ]
