# Generated by Django 5.1.7 on 2025-04-12 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_negocio', models.CharField(max_length=100, verbose_name='Nombre del Negocio')),
                ('direccion_negocio', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('ciudad_negocio', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ciudad')),
                ('telefono_negocio', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('email_negocio', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('ruc_negocio', models.CharField(blank=True, max_length=20, null=True, verbose_name='RUC/NIT')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='business_logos/', verbose_name='Logo')),
                ('iva_porcentaje', models.DecimalField(decimal_places=2, default=15.0, max_digits=5, verbose_name='Porcentaje de IVA')),
                ('mostrar_logo_en_factura', models.BooleanField(default=True, verbose_name='Mostrar Logo en Factura')),
                ('mensaje_factura', models.TextField(blank=True, default='¡Gracias por su compra!', null=True, verbose_name='Mensaje en Factura')),
                ('politica_devolucion', models.TextField(blank=True, default='Para devoluciones, presente este comprobante dentro de los próximos 7 días.', null=True, verbose_name='Política de Devolución')),
                ('moneda', models.CharField(default='$', max_length=10, verbose_name='Símbolo de Moneda')),
                ('formato_fecha', models.CharField(default='d/m/Y', max_length=20, verbose_name='Formato de Fecha')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Negocio',
                'verbose_name_plural': 'Configuraciones de Negocio',
            },
        ),
    ]
