# Generated by Django 5.2.7 on 2026-02-25 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_add_order_model'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='order',
            new_name='ventas_orde_busines_4cce2c_idx',
            old_name='ventas_orde_busines_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='ventas_orde_busines_06932f_idx',
            old_name='ventas_orde_busines_created_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='ventas_orde_status_322bd6_idx',
            old_name='ventas_orde_status_created_idx',
        ),
    ]
