# Generated by Django 4.2.28 on 2026-03-04 17:28

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0014_add_soft_delete_field'),
        ('ventas', '0003_rename_ventas_orde_busines_idx_ventas_orde_busines_4cce2c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='codigo_producto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='iva_porcentaje',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='nombre_producto',
            field=models.CharField(default='Producto', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.producto'),
        ),
    ]
