# Generated by Django 4.2.28 on 2026-03-04 17:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_detalleventa_codigo_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='costo_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=10, null=True),
        ),
    ]
