# Generated by Django 4.2.28 on 2026-03-04 21:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_create_punto_emision_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntoemision',
            name='codigo',
            field=models.CharField(help_text='3 dígitos (ej: 001, 002)', max_length=3, validators=[django.core.validators.RegexValidator(message='El código debe ser exactamente 3 dígitos numéricos (ej: 001, 002)', regex='^\\d{3}$')], verbose_name='Código Punto Emisión'),
        ),
        migrations.AlterField(
            model_name='puntoemision',
            name='establecimiento_codigo',
            field=models.CharField(help_text='3 dígitos (ej: 001)', max_length=3, validators=[django.core.validators.RegexValidator(message='El código debe ser exactamente 3 dígitos numéricos (ej: 001, 002)', regex='^\\d{3}$')], verbose_name='Código Establecimiento'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='numero_factura',
            field=models.CharField(blank=True, help_text='Formato: 001-001-000000001', max_length=17, null=True, verbose_name='Número de Factura'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='punto_emision',
            field=models.ForeignKey(blank=True, help_text='Punto de emisión que generó esta factura', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='ventas.puntoemision', verbose_name='Punto de Emisión'),
        ),
    ]
