# Generated by Django 4.2.28 on 2026-03-06 02:16

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0017_make_sku_required_and_unique'),
        ('ventas', '0008_remove_global_unique_numero_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='aplica_iva',
            field=models.BooleanField(default=True, verbose_name='Aplica IVA'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='descuento_monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Descuento $'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='descuento_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Descuento %'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='notas',
            field=models.TextField(blank=True, null=True, verbose_name='Notas Especiales'),
        ),
        migrations.AddField(
            model_name='venta',
            name='descuento_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Descuento Total'),
        ),
        migrations.AddField(
            model_name='venta',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Pago Parcial'), ('pagado', 'Pagado Completo')], default='pagado', max_length=20, verbose_name='Estado de Pago'),
        ),
        migrations.AddField(
            model_name='venta',
            name='recargo_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Recargo Total'),
        ),
        migrations.AddField(
            model_name='venta',
            name='saldo_pendiente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo Pendiente'),
        ),
        migrations.AddField(
            model_name='venta',
            name='tipo_comprobante',
            field=models.CharField(choices=[('ticket', 'Ticket'), ('factura', 'Factura Electrónica'), ('nota_venta', 'Nota de Venta')], default='ticket', max_length=20, verbose_name='Tipo de Comprobante'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='iva_porcentaje',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5, verbose_name='% IVA'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='productos.producto'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('cash', 'Efectivo'), ('card', 'Tarjeta'), ('transfer', 'Transferencia'), ('credit', 'Crédito')], default='cash', max_length=20),
        ),
    ]
