# Generated by Django 4.2.28 on 2026-03-06 02:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0019_alter_business_establecimiento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ventas', '0009_detalleventa_aplica_iva_detalleventa_descuento_monto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='iva_monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto IVA'),
        ),
        migrations.CreateModel(
            name='CajaSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Apertura')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cierre')),
                ('monto_inicial', models.DecimalField(decimal_places=2, help_text='Efectivo con el que se abre la caja', max_digits=10, verbose_name='Monto Inicial')),
                ('monto_esperado', models.DecimalField(decimal_places=2, default=0, help_text='Calculado: inicial + ventas cash - retiros', max_digits=10, verbose_name='Monto Esperado')),
                ('monto_real', models.DecimalField(blank=True, decimal_places=2, help_text='Efectivo contado al cerrar', max_digits=10, null=True, verbose_name='Monto Real')),
                ('diferencia', models.DecimalField(decimal_places=2, default=0, help_text='Real - Esperado (positivo = sobrante, negativo = faltante)', max_digits=10, verbose_name='Diferencia')),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada'), ('auditada', 'Auditada')], default='abierta', max_length=20, verbose_name='Estado')),
                ('notas_apertura', models.TextField(blank=True, null=True, verbose_name='Notas de Apertura')),
                ('notas_cierre', models.TextField(blank=True, null=True, verbose_name='Notas de Cierre')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caja_sesiones', to='usuarios.business', verbose_name='Negocio')),
                ('punto_emision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='caja_sesiones', to='ventas.puntoemision', verbose_name='Punto de Emisión')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caja_sesiones', to=settings.AUTH_USER_MODEL, verbose_name='Cajero')),
            ],
            options={
                'verbose_name': 'Sesión de Caja',
                'verbose_name_plural': 'Sesiones de Caja',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.AddField(
            model_name='venta',
            name='caja_sesion',
            field=models.ForeignKey(blank=True, help_text='Sesión de caja en la que se realizó esta venta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='ventas.cajasesion', verbose_name='Sesión de Caja'),
        ),
        migrations.AddIndex(
            model_name='cajasesion',
            index=models.Index(fields=['business', 'usuario', 'estado'], name='ventas_caja_busines_43cfbe_idx'),
        ),
        migrations.AddIndex(
            model_name='cajasesion',
            index=models.Index(fields=['fecha_apertura'], name='ventas_caja_fecha_a_6b02f1_idx'),
        ),
        migrations.AddIndex(
            model_name='cajasesion',
            index=models.Index(fields=['estado'], name='ventas_caja_estado_e0e0b6_idx'),
        ),
    ]
